### ISSUE TITLE
Suggestion: add t.Diagnostic()

### ISSUE THREAD

**Issue by tesujimath** [mndrix/tap-go#3]
I know it's only a printf wrapper, but it would be nice to have this:
```
// Diagnostic simply outputs the message
func (t *T) Diagnostic(message string) {
	t.printf("# %s\n", message)
}
```

**Comment by mndrix** [comment]
> it would be nice to have this:
>
> // Diagnostic simply outputs the message
> func (t *T) Diagnostic(message string) {
> 	t.printf("# %s\n", message)
> }

Good idea.  Feel free to send a pull request. If not, I should be able to
add it later this week.
